language: node_js
node_js:
- '10'
- '9'
- '8'
deploy:
  provider: npm
  email: duartecostamendes@gmail.com
  api_key:
    secure: NPe4lL2EqU/b1bnkmRhtWOTh6XeLMg5uyjfEDF6NvDk6QMWQzNGNwme4s6vmDEYZ2hSIfd+wAZWWiP9QixtlrRinPf036V3Baojzq3eRLL+U18BwGYKiqhLKOa84wvI+CA5AT398LIsPLqlzM1AQKfedVaor84uthcYhujwqTHLFz/s74Vs5H09jzzEeL7pz/hDI+zd0tNa5J8Ltb14HMJHEynbe+6CKuMnfGMd/Nf8ePA0DsR22frzPfRRiGrgiHBrYcf9QDMZlK+TbaSUU1MmImQSdEVrzHjrC8tHOxoVgYnrTv6EOL6vcRCoSI09xyjjdPYpugAd4ImZI8VE+cmxH29Cc/rKK0G79EdiicnlQet65Co83+s2WWiejlmGLvXjJOOeM0PPdnZn49W0YMRskyQnx661cIhUE6BsxeafeJm8zzEmP2sIWI3Bo8LP+H/Z2CObu/MCxDUb2DfLiy8TKBtGHlvXsaxnde38J7Erf1rCrOedNbewxjYXb24XFd46oVEvkOkEYWpkW4ne6AgY5XWxmoiPSZVpqqqnc2X5luj3dtn9qREa7rQTn3B1kATJ48Y5Vs7yBAwMVv90kI7sB5rmoUK1CUp8uU7RSVo1YfzBRQ05epNhRIE4xZQKw/TR7VjHNeEYWPtEgQGllH1sL7fLClsMt4+iesRmRtR4=
  on:
    tags: true
    repo: statful/statful-traffic-splitter
    branch: master
    node: '10'
